name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: | 
            echo "Hellow world2!"
            echo "It is alive"
      - name: Print goodye
        run: echo "Goddbye World!"
